### ISSUE TITLE
can't read my txt file

### ISSUE THREAD

**Issue by evainga** [evainga/practice#2]
@mle-enso
I can't read my txt file. I get FileNotFoundException, but the file is in the resources folder. Shouldn't my program find it there automaticely or what did I miss? see my new branch read-txt

**Comment by mle-enso** [comment]
You use http://docs.oracle.com/javase/7/docs/api/java/io/FileReader.html#FileReader(java.lang.String) to instantiate a FileReader... read the JavaDoc of this constructor...

> [...] given the name of the file to read from.

Ask yourself what directory is chosen, if you do not explicitly name one.

By the way the task was to use FileUtils of Apache Commons IO.

Try to build a File object by using this constructor http://docs.oracle.com/javase/7/docs/api/java/io/File.html#File(java.lang.String) with the pathname constructed by

`TxtReader.class.getResource("/guest-and-host.txt").getFile();`

**Comment by mle-enso** [comment]
If you need a hint on the solution, look into #3

**Comment by evainga** [comment]
mhm ok when I put "src/main/resources/guest-and-host.txt" it works... I just don't get why the path was not necessary in my tech-talker project
